spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto = validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
scheduling:
  enabled: true
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: WARN
authorization:
  token: ${TOKEN}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8084}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
  password: ${EUREKA_PASSWORD:password}
security:
  user:
    password: ${eureka.password}
---
spring:
  profiles: local
eureka:
  instance:
    nonSecurePort: 8083
